-- Create trades table
create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  symbol text not null,
  type text not null,
  "tradeDate" date not null,
  "entryDate" date,
  "exitDate" date,
  "entryPrice" numeric,
  "exitPrice" numeric,
  quantity numeric,
  "stopLoss" numeric,
  "takeProfit" numeric,
  session text,
  emotion text,
  confidence text,
  mistakes text,
  strategy text,
  tags text,
  notes text,
  screenshot text,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.trades enable row level security;

-- Create policies
create policy "Users can view their own trades"
  on public.trades for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own trades"
  on public.trades for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own trades"
  on public.trades for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own trades"
  on public.trades for delete
  using ( auth.uid() = user_id );
